class TocNode {
  const TocNode(this.title, this.printedPage, {this.children = const []});

  final String title;
  final int printedPage;
  final List<TocNode> children;
}

const bookContents = <TocNode>[
  TocNode('Primeira Parte · Doutrina', 11, children: [
    TocNode('Capítulo I · O porvir e o nada', 11),
    TocNode('Capítulo II · Temor da morte', 19, children: [
      TocNode('Causas do temor da morte', 19),
      TocNode('Por que os espíritas não temem a morte', 23),
    ]),
    TocNode('Capítulo III · O céu', 25),
    TocNode('Capítulo IV · O inferno', 37, children: [
      TocNode('Intuição das penas futuras', 37),
      TocNode('O inferno cristão imitado do inferno pagão', 38),
      TocNode('Os limbos', 40),
      TocNode('Quadro do inferno pagão', 41),
      TocNode('Esboço do inferno cristão', 48),
    ]),
    TocNode('Capítulo V · O purgatório', 57),
    TocNode('Capítulo VI · Doutrina das penas eternas', 63, children: [
      TocNode('Origem da doutrina das penas eternas', 63),
      TocNode('Argumentos a favor das penas eternas', 68),
      TocNode('Impossibilidade material das penas eternas', 72),
      TocNode('A doutrina das penas eternas fez sua época', 74),
      TocNode('Ezequiel contra a eternidade das penas e o pecado original', 76),
    ]),
    TocNode('Capítulo VII · As penas futuras segundo o Espiritismo', 79,
        children: [
      TocNode('A carne é fraca', 79),
      TocNode('Princípios da Doutrina Espírita sobre as penas futuras', 82),
      TocNode('Código penal da vida futura', 82),
    ]),
    TocNode('Capítulo VIII · Os anjos', 93, children: [
      TocNode('Os anjos segundo a Igreja', 93),
      TocNode('Refutação', 97),
      TocNode('Os anjos segundo o Espiritismo', 102),
    ]),
    TocNode('Capítulo IX · Os demônios', 105, children: [
      TocNode('Origem da crença nos demônios', 105),
      TocNode('Os demônios segundo a Igreja', 108),
      TocNode('Os demônios segundo o Espiritismo', 118),
    ]),
    TocNode('Capítulo X · Intervenção dos demônios nas modernas manifestações', 121),
    TocNode('Capítulo XI · Da proibição de evocar os mortos', 139),
  ]),
  TocNode('Segunda Parte · Exemplos', 151, children: [
    TocNode('Capítulo I · O passamento', 151),
    TocNode('Capítulo II · Espíritos felizes', 159, children: [
      TocNode('Sanson', 159),
      TocNode('Jobard', 168),
      TocNode('Samuel Philippe', 173),
      TocNode('Van Durst', 177),
      TocNode('Sixdeniers', 178),
      TocNode('O doutor Demeure', 181),
      TocNode('A viúva Foulon, nascida Wollis', 186),
      TocNode('Um médico russo', 193),
      TocNode('Bernardin', 197),
      TocNode('A condessa Paula', 198),
      TocNode('Jean Reynaud', 201),
      TocNode('Antoine Costeau', 205),
      TocNode('A Srta. Emma', 208),
      TocNode('O doutor Vignal', 209),
      TocNode('Victor Lebufle', 212),
      TocNode('A Sra. Anaïs Gourdon', 214),
      TocNode('Maurice Gontran', 215),
    ]),
    TocNode('Capítulo III · Espíritos em condições medianas', 219, children: [
      TocNode('Joseph Bré', 219),
      TocNode('Sra. Hélène Michel', 220),
      TocNode('O marquês de Saint-Paul', 222),
      TocNode('Sr. Cardon, médico', 224),
      TocNode('Eric Stanislas', 228),
      TocNode('Sra. Anna Belleville', 229),
    ]),
    TocNode('Capítulo IV · Espíritos sofredores', 235, children: [
      TocNode('O castigo', 235),
      TocNode('Novel', 237),
      TocNode('Auguste Michel', 238),
      TocNode('Exprobrações de um boêmio', 240),
      TocNode('Lisbeth', 241),
      TocNode('Príncipe Ouran', 244),
      TocNode('Pascal Lavic', 247),
      TocNode('Ferdinand Bertin', 248),
      TocNode('François Riquier', 252),
      TocNode('Claire', 253),
    ]),
    TocNode('Capítulo V · Suicidas', 263, children: [
      TocNode('O suicida da Samaritana', 263),
      TocNode('O pai e o conscrito', 265),
      TocNode('François-Simon Louvet', 268),
      TocNode('Mãe e filho', 269),
      TocNode('Duplo suicídio, por amor e por dever', 272),
      TocNode('Louis e a pespontadeira de botinas', 275),
      TocNode('Um ateu', 278),
      TocNode('Félicien', 284),
      TocNode('Antoine Bell', 287),
    ]),
    TocNode('Capítulo VI · Criminosos arrependidos', 293, children: [
      TocNode('Verger', 293),
      TocNode('Lemaire', 296),
      TocNode('Benoist', 299),
      TocNode('O Espírito de Castelnaudary', 302),
      TocNode('Jacques Latour', 308),
    ]),
    TocNode('Capítulo VII · Espíritos endurecidos', 321, children: [
      TocNode('Lapommeray', 321),
      TocNode('Angèle, nulidade sobre a Terra', 326),
      TocNode('Um Espírito aborrecido', 329),
      TocNode('A rainha de Oude', 331),
      TocNode('Xumène', 334),
    ]),
    TocNode('Capítulo VIII · Expiações terrestres', 337, children: [
      TocNode('Marcel, o menino do nº 4', 337),
      TocNode('Szymel Slizgol', 340),
      TocNode('Julienne-Marie, a mendiga', 345),
      TocNode('Max, o mendigo', 349),
      TocNode('História de um criado', 352),
      TocNode('Antonio B...', 354),
      TocNode('Letil', 357),
      TocNode('Um sábio ambicioso', 359),
      TocNode('Charles de Saint-G..., idiota', 361),
      TocNode('Adélaïde-Marguerite Gosse', 365),
      TocNode('Clara Rivier', 367),
      TocNode('Françoise Vernhes', 370),
      TocNode('Anna Bitter', 372),
      TocNode('Joseph Maître, o cego', 375),
    ]),
  ]),
  TocNode('Nota Explicativa', 379),
  TocNode('Índice Geral', 385),
];
