name: o_ceu_e_o_inferno
description: Leitura e busca em O Céu e o Inferno.
publish_to: none
version: 1.0.1+2

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter
  share_plus: 9.0.0
  shared_preferences: ^2.3.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/icon/icon.png
  min_sdk_android: 21
  adaptive_icon_background: "#3B2F63"
  adaptive_icon_foreground: assets/icon/icon_fg.png

flutter:
  uses-material-design: true
  assets:
    - assets/kardec.jpg
    - assets/book_content.json
